### ISSUE TITLE
`dcgm-exporter` panics while attempting to associate metrics with pods

### ISSUE THREAD

**Issue by cjgibson** [NVIDIA/dcgm-exporter#133]
Testing out an upgrade from DCGM 3.0.4 to 3.1.3 at the moment, hitting this issue:

```bash
Warning #2: dcgm-exporter doesn't have sufficient privileges to expose profiling metrics. To get profiling metrics with dcgm-exporter, use --cap-add SYS_ADMIN
time="2023-01-23T22:28:10Z" level=info msg="Starting dcgm-exporter"
time="2023-01-23T22:28:10Z" level=info msg="Attemping to connect to remote hostengine at localhost:5555"
time="2023-01-23T22:28:10Z" level=info msg="DCGM successfully initialized!"
time="2023-01-23T22:28:10Z" level=info msg="Collecting DCP Metrics"
time="2023-01-23T22:28:10Z" level=info msg="No configmap data specified, falling back to metric file /var/lib/dcgm-exporter-start/counters.csv"
time="2023-01-23T22:28:10Z" level=info msg="Initializing system entities of type: GPU"
time="2023-01-23T22:28:12Z" level=info msg="Initializing system entities of type: NvSwitch"
time="2023-01-23T22:28:12Z" level=info msg="Initializing system entities of type: NvLink"
time="2023-01-23T22:28:13Z" level=info msg="Kubernetes metrics collection enabled!"
time="2023-01-23T22:28:13Z" level=info msg="Pipeline starting"
time="2023-01-23T22:28:13Z" level=info msg="Starting webserver"
panic: assignment to entry in nil map

goroutine 148 [running]:
github.com/NVIDIA/dcgm-exporter/pkg/dcgmexporter.(*PodMapper).Process(_, {_, _, _}, {0x0, {{{0x0, {...}, {...}, 0x0, {...}, ...}, ...}, ...}, ...})
	/go/src/github.com/NVIDIA/dcgm-exporter/pkg/dcgmexporter/kubernetes.go:91 +0x65d
github.com/NVIDIA/dcgm-exporter/pkg/dcgmexporter.(*MetricsPipeline).run(0xc0002fe000)
	/go/src/github.com/NVIDIA/dcgm-exporter/pkg/dcgmexporter/pipeline.go:153 +0x716
github.com/NVIDIA/dcgm-exporter/pkg/dcgmexporter.(*MetricsPipeline).Run(0xc0002fe000, 0xc0005916e0, 0xc0005c80c0, 0x0)
	/go/src/github.com/NVIDIA/dcgm-exporter/pkg/dcgmexporter/pipeline.go:108 +0x18d
created by main.Run
	/go/src/github.com/NVIDIA/dcgm-exporter/cmd/dcgm-exporter/main.go:250 +0x5e5
```

Installed Nvidia driver is `525.60.13`:

<details>
<summary>nvidia-smi</summary>

```bash
# nvidia-smi
Mon Jan 23 22:44:31 2023
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.60.13    Driver Version: 525.60.13    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA A100-SXM...  On   | 00000001:00:00.0 Off |                    0 |
| N/A   29C    P0    50W / 400W |      0MiB / 40960MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA A100-SXM...  On   | 00000002:00:00.0 Off |                    0 |
| N/A   27C    P0    50W / 400W |      0MiB / 40960MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   2  NVIDIA A100-SXM...  On   | 00000003:00:00.0 Off |                    0 |
| N/A   28C    P0    51W / 400W |      0MiB / 40960MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   3  NVIDIA A100-SXM...  On   | 00000004:00:00.0 Off |                    0 |
| N/A   27C    P0    51W / 400W |      0MiB / 40960MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   4  NVIDIA A100-SXM...  On   | 0000000B:00:00.0 Off |                    0 |
| N/A   29C    P0    52W / 400W |      0MiB / 40960MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   5  NVIDIA A100-SXM...  On   | 0000000C:00:00.0 Off |                    0 |
| N/A   27C    P0    52W / 400W |      0MiB / 40960MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   6  NVIDIA A100-SXM...  On   | 0000000D:00:00.0 Off |                    0 |
| N/A   28C    P0    49W / 400W |      0MiB / 40960MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   7  NVIDIA A100-SXM...  On   | 0000000E:00:00.0 Off |                    0 |
| N/A   27C    P0    50W / 400W |      0MiB / 40960MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
# systemctl status nvidia-persistenced
● nvidia-persistenced.service - NVIDIA Persistence Daemon
   Loaded: loaded (/lib/systemd/system/nvidia-persistenced.service; static; vendor preset: enabled)
  Drop-In: /etc/systemd/system/nvidia-persistenced.service.d
           └─override.conf
   Active: active (running) since Mon 2023-01-23 21:37:15 UTC; 1h 10min ago
 Main PID: 5743 (nvidia-persiste)
    Tasks: 1 (limit: 17203)
   CGroup: /system.slice/nvidia-persistenced.service
           └─5743 /usr/bin/nvidia-persistenced --user nvidia-persistenced --persistence-mode --verbose

Jan 23 21:37:15 a100 nvidia-persistenced[5743]: device 000c:00:00.0 - persistence mode enabled.
Jan 23 21:37:15 a100 nvidia-persistenced[5743]: device 000c:00:00.0 - NUMA memory onlined.
Jan 23 21:37:15 a100 nvidia-persistenced[5743]: device 000d:00:00.0 - registered
Jan 23 21:37:15 a100 nvidia-persistenced[5743]: device 000d:00:00.0 - persistence mode enabled.
Jan 23 21:37:15 a100 nvidia-persistenced[5743]: device 000d:00:00.0 - NUMA memory onlined.
Jan 23 21:37:15 a100 nvidia-persistenced[5743]: device 000e:00:00.0 - registered
Jan 23 21:37:15 a100 nvidia-persistenced[5743]: device 000e:00:00.0 - persistence mode enabled.
Jan 23 21:37:15 a100 nvidia-persistenced[5743]: device 000e:00:00.0 - NUMA memory onlined.
Jan 23 21:37:15 a100 nvidia-persistenced[5743]: Local RPC services initialized
Jan 23 21:37:15 a100 systemd[1]: Started NVIDIA Persistence Daemon.
# systemctl status nvidia-fabricmanager
● nvidia-fabricmanager.service - NVIDIA fabric manager service
   Loaded: loaded (/lib/systemd/system/nvidia-fabricmanager.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2023-01-23 21:37:25 UTC; 1h 10min ago
 Main PID: 6040 (nv-fabricmanage)
    Tasks: 18 (limit: 17203)
   CGroup: /system.slice/nvidia-fabricmanager.service
           └─6040 /usr/bin/nv-fabricmanager -c /usr/share/nvidia/nvswitch/fabricmanager.cfg

Jan 23 21:36:54 a100 systemd[1]: Starting NVIDIA fabric manager service...
Jan 23 21:37:25 a100 nv-fabricmanager[6040]: Successfully configured all the available GPUs and NVSwitches to route NVLink traffic.
Jan 23 21:37:25 a100 systemd[1]: Started NVIDIA fabric manager service.
# systemctl status nvidia-dcgm
● nvidia-dcgm.service - NVIDIA DCGM service
   Loaded: loaded (/usr/lib/systemd/system/nvidia-dcgm.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/nvidia-dcgm.service.d
           └─override.conf
   Active: active (running) since Mon 2023-01-23 22:44:22 UTC; 3min 7s ago
  Process: 91222 ExecStartPost=/usr/bin/dcgmi health -s a (code=exited, status=0/SUCCESS)
  Process: 91168 ExecStartPost=/bin/sleep 3 (code=exited, status=0/SUCCESS)
 Main PID: 91167 (nv-hostengine)
    Tasks: 8 (limit: 17203)
   CGroup: /system.slice/nvidia-dcgm.service
           └─91167 /usr/bin/nv-hostengine -n --service-account nvidia-dcgm

Jan 23 22:44:17 a100 systemd[1]: Starting NVIDIA DCGM service...
Jan 23 22:44:18 a100 nv-hostengine[91167]: DCGM initialized
Jan 23 22:44:18 a100 nv-hostengine[91167]: Started host engine version 3.1.3 using port number: 5555
Jan 23 22:44:22 a100 dcgmi[91222]: Health monitor systems set successfully.
Jan 23 22:44:22 a100 systemd[1]: Started NVIDIA DCGM service.
```

</details>

And our configuration file is as shown:

<details>
<summary>counters.csv</summary>

```bash
# Format,,
# If line starts with a '#' it is considered a comment,,
# DCGM FIELD, Prometheus metric type, help message

# Count,,
DCGM_FI_DEV_COUNT, gauge, Number of Devices on the node.

# Clocks,,
DCGM_FI_DEV_SM_CLOCK,  gauge, SM clock frequency (in MHz).
DCGM_FI_DEV_MEM_CLOCK, gauge, Memory clock frequency (in MHz).

# Temperature,,
DCGM_FI_DEV_MEMORY_TEMP, gauge, Memory temperature (in C).
DCGM_FI_DEV_GPU_TEMP,    gauge, GPU temperature (in C).

# Power,,
DCGM_FI_DEV_POWER_USAGE,              gauge,   Power draw (in W).
DCGM_FI_DEV_TOTAL_ENERGY_CONSUMPTION, counter, Total energy consumption since boot (in mJ).

# PCIE,,
DCGM_FI_DEV_PCIE_REPLAY_COUNTER, counter, Total number of PCIe retries.
DCGM_FI_PROF_PCIE_TX_BYTES,      counter, The number of bytes of active PCIe tx (transmit) data including both header and payload.
DCGM_FI_PROF_PCIE_RX_BYTES,      counter, The number of bytes of active PCIe rx (read) data including both header and payload.

# Utilization (the sample period varies depending on the product),,
DCGM_FI_DEV_GPU_UTIL,      gauge, GPU utilization (in %).
DCGM_FI_DEV_MEM_COPY_UTIL, gauge, Memory utilization (in %).
DCGM_FI_DEV_ENC_UTIL,      gauge, Encoder utilization (in %).
DCGM_FI_DEV_DEC_UTIL ,     gauge, Decoder utilization (in %).

# Errors and violations,,
DCGM_FI_DEV_XID_ERRORS,            gauge,   Value of the last XID error encountered.
DCGM_FI_DEV_POWER_VIOLATION,       counter, Throttling duration due to power constraints (in us).
DCGM_FI_DEV_THERMAL_VIOLATION,     counter, Throttling duration due to thermal constraints (in us).
DCGM_FI_DEV_SYNC_BOOST_VIOLATION,  counter, Throttling duration due to sync-boost constraints (in us).
DCGM_FI_DEV_BOARD_LIMIT_VIOLATION, counter, Throttling duration due to board limit constraints (in us).
DCGM_FI_DEV_LOW_UTIL_VIOLATION,    counter, Throttling duration due to low utilization (in us).
DCGM_FI_DEV_RELIABILITY_VIOLATION, counter, Throttling duration due to reliability constraints (in us).
DCGM_FI_DEV_CLOCK_THROTTLE_REASONS,  gauge, bitmask of all throttle reasons

# Memory usage,,
DCGM_FI_DEV_FB_FREE,     gauge, Framebuffer memory free (in MiB).
DCGM_FI_DEV_FB_USED,     gauge, Framebuffer memory used (in MiB).
# DCGM_FI_DEV_FB_RESERVED, gauge, Framebuffer memory reserved (in MiB).

# ECC,,
# DCGM_FI_DEV_ECC_SBE_VOL_TOTAL, counter, Total number of single-bit volatile ECC errors.
# DCGM_FI_DEV_ECC_DBE_VOL_TOTAL, counter, Total number of double-bit volatile ECC errors.
# DCGM_FI_DEV_ECC_SBE_AGG_TOTAL, counter, Total number of single-bit persistent ECC errors.
# DCGM_FI_DEV_ECC_DBE_AGG_TOTAL, counter, Total number of double-bit persistent ECC errors.

# Retired pages,,
# DCGM_FI_DEV_RETIRED_SBE,     counter, Total number of retired pages due to single-bit errors.
# DCGM_FI_DEV_RETIRED_DBE,     counter, Total number of retired pages due to double-bit errors.
# DCGM_FI_DEV_RETIRED_PENDING, counter, Total number of pages pending retirement.

# NVLink,,
DCGM_FI_DEV_NVLINK_CRC_FLIT_ERROR_COUNT_TOTAL, counter, Total number of NVLink flow-control CRC errors.
DCGM_FI_DEV_NVLINK_CRC_DATA_ERROR_COUNT_TOTAL, counter, Total number of NVLink data CRC errors.
DCGM_FI_DEV_NVLINK_REPLAY_ERROR_COUNT_TOTAL,   counter, Total number of NVLink retries.
DCGM_FI_DEV_NVLINK_RECOVERY_ERROR_COUNT_TOTAL, counter, Total number of NVLink recovery errors.
DCGM_FI_PROF_NVLINK_RX_BYTES,                  gauge,   The number of bytes of active NVLink rx (read) data including both header and payload.
DCGM_FI_PROF_NVLINK_TX_BYTES,                  gauge,   The number of bytes of active NVLink tx (write) data including both header and payload.
# DCGM_FI_PROF_PCIE_TX_BYTES,                    gauge,   The number of bytes of active PCIe tx (transmit) data including both header and payload.
# DCGM_FI_PROF_PCIE_RX_BYTES,                    gauge,   The number of bytes of active PCIe rx (read) data including both header and payload.

# NVSwitch,,
DCGM_FI_DEV_NVSWITCH_FATAL_ERRORS,          gauge,   Value of the last fatal SXID error encountered.
DCGM_FI_DEV_NVSWITCH_NON_FATAL_ERRORS,      gauge,   Value of the last non-fatal SXID error encountered.
DCGM_FI_DEV_NVSWITCH_LINK_FATAL_ERRORS,     gauge,   NVSwitch fatal_errors for ports 0-17
DCGM_FI_DEV_NVSWITCH_LINK_NON_FATAL_ERRORS, gauge,   NVSwitch non_fatal_errors for ports 0-17
DCGM_FI_DEV_NVSWITCH_LINK_REPLAY_ERRORS,    gauge,   NVSwitch replay_count_errors for ports 0-17
DCGM_FI_DEV_NVSWITCH_LINK_RECOVERY_ERRORS,  gauge,   NVSwitch recovery_count_errors for ports 0-17
DCGM_FI_DEV_NVSWITCH_LINK_FLIT_ERRORS,      gauge,   NVSwitch filt_err_count_errors for ports 0-17
DCGM_FI_DEV_NVSWITCH_LINK_CRC_ERRORS,       gauge,   NVLink lane_crs_err_count_aggregate_errors for ports 0-17
DCGM_FI_DEV_NVSWITCH_LINK_ECC_ERRORS,       gauge,   NVLink lane ecc_err_count_aggregate_errors for ports 0-17
DCGM_FI_DEV_NVSWITCH_TEMPERATURE_CURRENT,   gauge,   NVSwitch current temperature
# DCGM_FI_DEV_NVSWITCH_RESET_REQUIRED,        gauge,   NVSwitch reset required
DCGM_FI_DEV_NVSWITCH_THROUGHPUT_TX,         gauge,   NVSwitch throughput tx
DCGM_FI_DEV_NVSWITCH_THROUGHPUT_RX,         gauge,   NVSwitch throughput rx
DCGM_FI_DEV_NVSWITCH_LINK_THROUGHPUT_TX,    gauge,   NVSwitch link throughput tx
DCGM_FI_DEV_NVSWITCH_LINK_THROUGHPUT_RX,    gauge,   NVSwitch link throughput rx

# VGPU License status,,
DCGM_FI_DEV_VGPU_LICENSE_STATUS, gauge, vGPU License status

# Remapped rows,,
DCGM_FI_DEV_UNCORRECTABLE_REMAPPED_ROWS, counter, Number of remapped rows for uncorrectable errors
DCGM_FI_DEV_CORRECTABLE_REMAPPED_ROWS,   counter, Number of remapped rows for correctable errors
DCGM_FI_DEV_ROW_REMAP_FAILURE,           gauge,   Whether remapping of rows has failed
```

</details>

`kubelet` local to the host is running version `v1.21.3`.

**Comment by glowkey** [comment]
We have not seen this in our testing and this particular section of code hasn't changed recently. What values are you passing to dcgm-exporter for startup?

**Comment by cjgibson** [comment]
Yeah, I had noticed that - weird thing is `3.0.4` (`nvidia/dcgm-exporter:3.0.4-3.0.0-ubuntu20.04`) works without issue, it's just `3.1.3` (`nvidia/dcgm-exporter:3.1.3-3.1.2-ubuntu20.04`) that seems to have problems.

Our startup here is just:

```bash
/usr/local/dcgm/dcgm-exporter-entrypoint.sh -f /var/lib/dcgm-exporter-start/counters.csv
```

With envvars:

```bash
DCGM_EXPORTER_KUBERNETES="true"
DCGM_EXPORTER_LISTEN=":9400"
DCGM_EXPORTER_INTERVAL="30000"
DCGM_REMOTE_HOSTENGINE_INFO="localhost:5555"
```

**Comment by glowkey** [comment]
Could you test the latest 3.1.6-3.1.3 release and confirm if the panic is gone?

**Comment by cjgibson** [comment]
Yep, not likely today - but I'll attempt and hit this before the middle of next week. I'll reconfirm the issue with `3.1.3-3.1.2` beforehand to try and see if there was something I messed up previously. I've just been running `3.0.4-3.0.0` and outside of not getting a couple of fun new metrics, that seems to be running fine.

**Comment by cjgibson** [comment]
> Could you test the latest 3.1.6-3.1.3 release and confirm if the panic is gone?

Apologies for the wait here, I can confirm this appears resolved on the latest release. Thanks!
