### ISSUE TITLE
Panic during start up in EKS [3.3.3-3.3.0]

### ISSUE THREAD

**Issue by movence** [NVIDIA/dcgm-exporter#245]
We are seeing dcgm-exporter getting into crash loop during start up in EKS. The error:
```
time="2024-01-31T18:28:05Z" level=info msg="Starting dcgm-exporter"                                                                            │
│ time="2024-01-31T18:28:05Z" level=info msg="DCGM successfully initialized!"                                                                    │
│ time="2024-01-31T18:28:05Z" level=info msg="Collecting DCP Metrics"                                                                            │
│ time="2024-01-31T18:28:05Z" level=info msg="No configmap data specified, falling back to metric file /etc/dcgm-exporter/dcp-metrics-included.c │
│ time="2024-01-31T18:28:05Z" level=info msg="Initializing system entities of type: GPU"                                                         │
│ time="2024-01-31T18:28:05Z" level=info msg="Initializing system entities of type: NvSwitch"                                                    │
│ time="2024-01-31T18:28:05Z" level=info msg="Not collecting switch metrics: no switches to monitor"                                             │
│ time="2024-01-31T18:28:05Z" level=info msg="Initializing system entities of type: NvLink"                                                      │
│ time="2024-01-31T18:28:05Z" level=info msg="Not collecting link metrics: no switches to monitor"                                               │
│ time="2024-01-31T18:28:05Z" level=info msg="Initializing system entities of type: CPU"                                                         │
│ SIGSEGV: segmentation violation                                                                                                                │
│ PC=0x7f45d6bb86aa m=0 sigcode=1                                                                                                                │
│ signal arrived during cgo execution                                                                                                            │
│                                                                                                                                                │
│ goroutine 1 [syscall]:                                                                                                                         │
│ runtime.cgocall(0x1203070, 0xc0005fdec0)                                                                                                       │
│     /usr/local/go/src/runtime/cgocall.go:157 +0x4b fp=0xc0005fde98 sp=0xc0005fde60 pc=0x41714b                                                 │
│ github.com/NVIDIA/go-dcgm/pkg/dcgm._Cfunc_dcgmGetCpuHierarchy(0x7fffffff, 0xc00002e000)                                                        │
│     _cgo_gotypes.go:1095 +0x4b fp=0xc0005fdec0 sp=0xc0005fde98 pc=0x58888b                                                                     │
│ github.com/NVIDIA/go-dcgm/pkg/dcgm.GetCpuHierarchy()                                                                                           │
│     /go/pkg/mod/github.com/!n!v!i!d!i!a/go-dcgm@v0.0.0-20240108230649-3c233ee2a242/pkg/dcgm/cpu.go:42 +0x6b fp=0xc0005feb70 sp=0xc0005fdec0 pc │
│ github.com/NVIDIA/dcgm-exporter/pkg/dcgmexporter.InitializeCPUInfo({0x0, {{{0x0, {...}, {...}, 0x0, {...}, {...}, {...}, {...}}, {0x0, ...}, . │
│     /go/src/github.com/NVIDIA/dcgm-exporter/pkg/dcgmexporter/system_info.go:296 +0x9f fp=0xc0005feee0 sp=0xc0005feb70 pc=0x11cfe1f             │
│ github.com/NVIDIA/dcgm-exporter/pkg/dcgmexporter.InitializeSystemInfo({_, {_, _, _}, {_, _, _}}, {0x1, {0x0, 0x0, ...}, ...}, ...)             │
│     /go/src/github.com/NVIDIA/dcgm-exporter/pkg/dcgmexporter/system_info.go:440 +0x4f9 fp=0xc000607308 sp=0xc0005feee0 pc=0x11d1599            │
│ github.com/NVIDIA/dcgm-exporter/pkg/dcgmexporter.NewDCGMCollector({0xc000269b80?, 0x19, 0x19}, 0xc0004611e0, 0x2?)                             │
│     /go/src/github.com/NVIDIA/dcgm-exporter/pkg/dcgmexporter/gpu_collector.go:30 +0x1e5 fp=0xc00060d7b8 sp=0xc000607308 pc=0x11c6d45           │
│ github.com/NVIDIA/dcgm-exporter/pkg/dcgmexporter.NewMetricsPipeline(0xc0004611e0, 0x159f770)                                                   │
│     /go/src/github.com/NVIDIA/dcgm-exporter/pkg/dcgmexporter/pipeline.go:58 +0x41d fp=0xc00060d9a8 sp=0xc00060d7b8 pc=0x11cc5fd                │
│ github.com/NVIDIA/dcgm-exporter/pkg/cmd.action(0xc000160a01?)                                                                                  │
│     /go/src/github.com/NVIDIA/dcgm-exporter/pkg/cmd/app.go:245 +0x445 fp=0xc00060dba0 sp=0xc00060d9a8 pc=0x12015a5                             │
│ github.com/NVIDIA/dcgm-exporter/pkg/cmd.NewApp.func1(0xc000461080?)                                                                            │
│     /go/src/github.com/NVIDIA/dcgm-exporter/pkg/cmd/app.go:193 +0x13 fp=0xc00060dbb8 sp=0xc00060dba0 pc=0x1202bd3                              │
│ github.com/urfave/cli/v2.(*Command).Run(0xc000461080, 0xc000160ac0, {0xc00018e050, 0x1, 0x1})                                                  │
│     /go/pkg/mod/github.com/urfave/cli/v2@v2.26.0/command.go:277 +0x9d8 fp=0xc00060de48 sp=0xc00060dbb8 pc=0x11ef5b8                            │
│ github.com/urfave/cli/v2.(*App).RunContext(0xc000000000, {0x16e1608?, 0x210b4a0}, {0xc00018e050, 0x1, 0x1})                                    │
│     /go/pkg/mod/github.com/urfave/cli/v2@v2.26.0/app.go:335 +0x5db fp=0xc00060deb0 sp=0xc00060de48 pc=0x11ebefb                                │
│ github.com/urfave/cli/v2.(*App).Run(0xc0004b7f20?, {0xc00018e050?, 0x1?, 0x1203e10?})                                                          │
│     /go/pkg/mod/github.com/urfave/cli/v2@v2.26.0/app.go:309 +0x2f fp=0xc00060def0 sp=0xc00060deb0 pc=0x11eb8cf                                 │
│ main.main()                                                                                                   
/go/src/github.com/NVIDIA/dcgm-exporter/cmd/dcgm-exporter/main.go:32 +0x5f fp=0xc00060df40 sp=0xc00060def0 pc=0x1202d3f                    │
│ runtime.main()                                                                                                                                 │
│     /usr/local/go/src/runtime/proc.go:267 +0x2bb fp=0xc00060dfe0 sp=0xc00060df40 pc=0x44c7db                                                   │
│ runtime.goexit()                                                                                                                               │
│     /usr/local/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc00060dfe8 sp=0xc00060dfe0 pc=0x47c701                                                │
│                                                                                                                                                │
│ goroutine 2 [force gc (idle)]:                                                                                                                 │
│ runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)                                                                                                   │
│     /usr/local/go/src/runtime/proc.go:398 +0xce fp=0xc000076fa8 sp=0xc000076f88 pc=0x44cc2e                                                    │
│ runtime.goparkunlock(...)                                                                                                                      │
│     /usr/local/go/src/runtime/proc.go:404                                                                                                      │
│ runtime.forcegchelper()                                                                                                                        │
│     /usr/local/go/src/runtime/proc.go:322 +0xb3 fp=0xc000076fe0 sp=0xc000076fa8 pc=0x44cab3                                                    │
│ runtime.goexit()                                                                                                                               │
│     /usr/local/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc000076fe8 sp=0xc000076fe0 pc=0x47c701                                                │
│ created by runtime.init.6 in goroutine 1                                                                                                       │
│     /usr/local/go/src/runtime/proc.go:310 +0x1a                                                                                                │
│                                                                                                                                                │
│ goroutine 3 [GC sweep wait]:                                                                                                                   │
│ runtime.gopark(0x1?, 0x0?, 0x0?, 0x0?, 0x0?)                                                                                                   │
│     /usr/local/go/src/runtime/proc.go:398 +0xce fp=0xc000077778 sp=0xc000077758 pc=0x44cc2e                                                    │
│ runtime.goparkunlock(...)                                                                                                                      │
│     /usr/local/go/src/runtime/proc.go:404                                                                                                      │
│ runtime.bgsweep(0x0?)                                                                                                                          │
│     /usr/local/go/src/runtime/mgcsweep.go:321 +0xdf fp=0xc0000777c8 sp=0xc000077778 pc=0x437d1f                                                │
│ runtime.gcenable.func1()                                                                                                                       │
│     /usr/local/go/src/runtime/mgc.go:200 +0x25 fp=0xc0000777e0 sp=0xc0000777c8 pc=0x42ce85                                                     │
│ runtime.goexit()                                                                                                                               │
│     /usr/local/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc0000777e8 sp=0xc0000777e0 pc=0x47c701                                                │
│ created by runtime.gcenable in goroutine 1                                                                                                     │
│     /usr/local/go/src/runtime/mgc.go:200 +0x66                                                                                                 │
│                                                                                                                                                │
│ goroutine 4 [GC scavenge wait]:                                                                                                                │
│ runtime.gopark(0xc000052070?, 0x16c61b0?, 0x0?, 0x0?, 0x0?)                                                                                    │
│     /usr/local/go/src/runtime/proc.go:398 +0xce fp=0xc000077f70 sp=0xc000077f50 pc=0x44cc2e                                                    │
│ runtime.goparkunlock(...)                                                                                                                      │
│     /usr/local/go/src/runtime/proc.go:404                                                                                                      │
│ runtime.(*scavengerState).park(0x20db7e0)                                                                                                      │
│     /usr/local/go/src/runtime/mgcscavenge.go:425 +0x49 fp=0xc000077fa0 sp=0xc000077f70 pc=0x4355a9
....(truncated)
│ rax    0x0                                                                                                                                     │
│ rbx    0x7f4564dbb360                                                                                                                          │
│ rcx    0x7f45d6bebc0c                                                                                                                          │
│ rdx    0x1                                                                                                                                     │
│ rdi    0x0                                                                                                                                     │
│ rsi    0x228b8c0                                                                                                                               │
│ rbp    0x4                                                                                                                                     │
│ rsp    0x7fff92262f60                                                                                                                          │
│ r8     0x90800                                                                                                                                 │
│ r9     0x228b8c0                                                                                                                               │
│ r10    0x0                                                                                                                                     │
│ r11    0x287                                                                                                                                   │
│ r12    0xffffffffffffff78                                                                                                                      │
│ r13    0x2                                                                                                                                     │
│ r14    0x0                                                                                                                                     │
│ r15    0x0                                                                                                                                     │
│ rip    0x7f45d6bb86aa                                                                                                                          │
│ rflags 0x10206                                                                                                                                 │
│ cs     0x33                                                                                                                                    │
│ fs     0x0                                                                                                                                     │
│ gs     0x0
```
The previous version `3.3.0-3.2.0-ubuntu22.04` doesn't seem to have this issue. I would like understand if there must be a tweak to be made when upgrading between versions. Any pointers would be appreciated!

-----
- dcgm-exporter: `3.3.3-3.3.0-ubuntu22.04`
- k8s: `1.28`
- container spec:
```
      containers:
      - name: dcgm-exporter
        securityContext:
          privileged: true
        image: "nvcr.io/nvidia/k8s/dcgm-exporter:3.3.3-3.3.0-ubuntu22.04"
        env:
        - name: "DCGM_EXPORTER_KUBERNETES"
          value: "true"
        - name: "DCGM_EXPORTER_LISTEN"
          value: ":9400"
        - name: "DCGM_EXPORTER_COLLECTORS"
          value: "/etc/dcgm-exporter/dcp-metrics-included.csv"
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        ports:
        - name: "metrics"
          containerPort: 9400
        volumeMounts:
        - name: "pod-gpu-resources"
          readOnly: true
          mountPath: "/var/lib/kubelet/pod-resources"
      volumes:
      - name: "pod-gpu-resources"
        hostPath:
          path: /var/lib/kubelet/pod-resources
      resources:
        requests:
          cpu: 250m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 250Mi
```

**Comment by peterbueschel** [comment]
Same for us. After the update yesterday to `3.3.3-3.3.0`, the container is crashlooping in our EKS cluster, with exactly the same error log.
