### ISSUE TITLE
SIGSEGV: segmentation violation

### ISSUE THREAD

**Issue by amybachir** [NVIDIA/dcgm-exporter#318]
### What is the version?

3.3.5-3.4.1

### What happened?

Upgraded from k8s 1.24 to 1.25 and dcgm-exporter from 3.3.3-3.3.1 to 3.3.5-3.4.1.
The dcgm-exporter  pod is now in Crashloopbackoff with this error:
```
2024/04/26 17:56:09 maxprocs: Updating GOMAXPROCS=1: using minimum allowed GOMAXPROCS
time="2024-04-26T17:56:09Z" level=info msg="Starting dcgm-exporter"
time="2024-04-26T17:56:09Z" level=info msg="DCGM successfully initialized!"
time="2024-04-26T17:56:09Z" level=info msg="Collecting DCP Metrics"
time="2024-04-26T17:56:09Z" level=warning msg="Skipping line 26 ('DCGM_FI_PROF_PIPE_FP64_ACTIVE'): metric not enabled"
time="2024-04-26T17:56:09Z" level=info msg="Initializing system entities of type: GPU"
time="2024-04-26T17:56:10Z" level=info msg="Initializing system entities of type: NvSwitch"
time="2024-04-26T17:56:10Z" level=info msg="Not collecting NvSwitch metrics; no switches to monitor"
time="2024-04-26T17:56:10Z" level=info msg="Initializing system entities of type: NvLink"
time="2024-04-26T17:56:10Z" level=info msg="Not collecting NvLink metrics; no switches to monitor"
time="2024-04-26T17:56:10Z" level=info msg="Initializing system entities of type: CPU"
SIGSEGV: segmentation violation
PC=0x7f98af7d96aa m=5 sigcode=1
signal arrived during cgo execution

goroutine 1 [syscall]:
runtime.cgocall(0x1615c80, 0xc0005cdc58)
	/usr/local/go/src/runtime/cgocall.go:157 +0x4b fp=0xc0005cdc30 sp=0xc0005cdbf8 pc=0x41816b
github.com/NVIDIA/go-dcgm/pkg/dcgm._Cfunc_dcgmGetCpuHierarchy(0x7fffffff, 0xc000497900)
	_cgo_gotypes.go:1115 +0x4b fp=0xc0005cdc58 sp=0xc0005cdc30 pc=0x7c786b
github.com/NVIDIA/go-dcgm/pkg/dcgm.GetCpuHierarchy()
	/go/pkg/mod/github.com/!n!v!i!d!i!a/go-dcgm@v0.0.0-20240118201113-3385e277e49f/pkg/dcgm/cpu.go:42 +0x6b fp=0xc0005ce908 sp=0xc0005cdc58 pc=0x7ca16b
github.com/NVIDIA/dcgm-exporter/pkg/dcgmexporter.InitializeCPUInfo({0x0, {{{0x0, {...}, {...}, 0x0, {...}, {...}, {...}, {...}}, {0x0, ...}, ...}, ...}, ...}, ...)
	/go/src/github.com/NVIDIA/dcgm-exporter/pkg/dcgmexporter/system_info.go:292 +0x9f fp=0xc0005cec88 sp=0xc0005ce908 pc=0x16086df
github.com/NVIDIA/dcgm-exporter/pkg/dcgmexporter.InitializeSystemInfo({_, {_, _, _}, {_, _, _}}, {0x1, {0x0, 0x0, ...}, ...}, ...)
	/go/src/github.com/NVIDIA/dcgm-exporter/pkg/dcgmexporter/system_info.go:448 +0x4f9 fp=0xc0005d70b0 sp=0xc0005cec88 pc=0x1609ff9
github.com/NVIDIA/dcgm-exporter/pkg/dcgmexporter.GetSystemInfo(0xc0005dd560, 0x2c?)
	/go/src/github.com/NVIDIA/dcgm-exporter/pkg/dcgmexporter/gpu_collector.go:68 +0x1dd fp=0xc0005dd4f8 sp=0xc0005d70b0 pc=0x15feadd
github.com/NVIDIA/dcgm-exporter/pkg/dcgmexporter.(*FieldEntityGroupTypeSystemInfo).Load(0xc0000d04e0, 0x7)
	/go/src/github.com/NVIDIA/dcgm-exporter/pkg/dcgmexporter/field_entity_group_system_info.go:73 +0x1a5 fp=0xc0005df7f8 sp=0xc0005dd4f8 pc=0x15fe285
github.com/NVIDIA/dcgm-exporter/pkg/cmd.getFieldEntityGroupTypeSystemInfo(0xc000384930, 0xc000103ba0)
	/go/src/github.com/NVIDIA/dcgm-exporter/pkg/cmd/app.go:410 +0x2ee fp=0xc0005df8e0 sp=0xc0005df7f8 pc=0x161342e
github.com/NVIDIA/dcgm-exporter/pkg/cmd.startDCGMExporter(0x47c312?, 0xc0004873e0)
	/go/src/github.com/NVIDIA/dcgm-exporter/pkg/cmd/app.go:301 +0x15d fp=0xc0005dfa60 sp=0xc0005df8e0 pc=0x16122fd
github.com/NVIDIA/dcgm-exporter/pkg/cmd.action.func1()
	/go/src/github.com/NVIDIA/dcgm-exporter/pkg/cmd/app.go:273 +0x5b fp=0xc0005dfab0 sp=0xc0005dfa60 pc=0x161201b
github.com/NVIDIA/dcgm-exporter/pkg/stdout.Capture({0x1cbea38?, 0xc000435770}, 0xc00025bb70)
	/go/src/github.com/NVIDIA/dcgm-exporter/pkg/stdout/capture.go:77 +0x1f5 fp=0xc0005dfb48 sp=0xc0005dfab0 pc=0x160fa75
github.com/NVIDIA/dcgm-exporter/pkg/cmd.action(0xc00046a0c0)
	/go/src/github.com/NVIDIA/dcgm-exporter/pkg/cmd/app.go:264 +0x67 fp=0xc0005dfba0 sp=0xc0005dfb48 pc=0x1611f87
github.com/NVIDIA/dcgm-exporter/pkg/cmd.NewApp.func1(0xc0004722c0?)
	/go/src/github.com/NVIDIA/dcgm-exporter/pkg/cmd/app.go:249 +0x13 fp=0xc0005dfbb8 sp=0xc0005dfba0 pc=0x16155b3
github.com/urfave/cli/v2.(*Command).Run(0xc0004722c0, 0xc00046a0c0, {0xc000040150, 0x3, 0x3})
	/go/pkg/mod/github.com/urfave/cli/v2@v2.27.1/command.go:279 +0x9dd fp=0xc0005dfe48 sp=0xc0005dfbb8 pc=0x7ed71d
github.com/urfave/cli/v2.(*App).RunContext(0xc0001c9800, {0x1cbe920?, 0x29c22a0}, {0xc000040150, 0x3, 0x3})
	/go/pkg/mod/github.com/urfave/cli/v2@v2.27.1/app.go:337 +0x5db fp=0xc0005dfeb0 sp=0xc0005dfe48 pc=0x7ea05b
github.com/urfave/cli/v2.(*App).Run(0xc00025bf20?, {0xc000040150?, 0x1?, 0x1616830?})
	/go/pkg/mod/github.com/urfave/cli/v2@v2.27.1/app.go:311 +0x2f fp=0xc0005dfef0 sp=0xc0005dfeb0 pc=0x7e9a2f
main.main()
	/go/src/github.com/NVIDIA/dcgm-exporter/cmd/dcgm-exporter/main.go:35 +0x5f fp=0xc0005dff40 sp=0xc0005dfef0 pc=0x161589f
runtime.main()
	/usr/local/go/src/runtime/proc.go:267 +0x2bb fp=0xc0005dffe0 sp=0xc0005dff40 pc=0x44e1fb
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc0005dffe8 sp=0xc0005dffe0 pc=0x47e2a1

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:398 +0xce fp=0xc000086fa8 sp=0xc000086f88 pc=0x44e64e
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:404
runtime.forcegchelper()
	/usr/local/go/src/runtime/proc.go:322 +0xb3 fp=0xc000086fe0 sp=0xc000086fa8 pc=0x44e4d3
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc000086fe8 sp=0xc000086fe0 pc=0x47e2a1
created by runtime.init.6 in goroutine 1
	/usr/local/go/src/runtime/proc.go:310 +0x1a

goroutine 3 [GC sweep wait]:
runtime.gopark(0x1?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:398 +0xce fp=0xc000087778 sp=0xc000087758 pc=0x44e64e
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:404
runtime.bgsweep(0x0?)
	/usr/local/go/src/runtime/mgcsweep.go:321 +0xdf fp=0xc0000877c8 sp=0xc000087778 pc=0x43969f
runtime.gcenable.func1()
	/usr/local/go/src/runtime/mgc.go:200 +0x25 fp=0xc0000877e0 sp=0xc0000877c8 pc=0x42e805
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc0000877e8 sp=0xc0000877e0 pc=0x47e2a1
created by runtime.gcenable in goroutine 1
	/usr/local/go/src/runtime/mgc.go:200 +0x66

goroutine 4 [GC scavenge wait]:
runtime.gopark(0xc0000520e0?, 0x1c9ecf0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:398 +0xce fp=0xc000087f70 sp=0xc000087f50 pc=0x44e64e
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:404
runtime.(*scavengerState).park(0x29925a0)
	/usr/local/go/src/runtime/mgcscavenge.go:425 +0x49 fp=0xc000087fa0 sp=0xc000087f70 pc=0x436f29
runtime.bgscavenge(0x0?)
	/usr/local/go/src/runtime/mgcscavenge.go:658 +0x59 fp=0xc000087fc8 sp=0xc000087fa0 pc=0x4374d9
runtime.gcenable.func2()
	/usr/local/go/src/runtime/mgc.go:201 +0x25 fp=0xc000087fe0 sp=0xc000087fc8 pc=0x42e7a5
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc000087fe8 sp=0xc000087fe0 pc=0x47e2a1
created by runtime.gcenable in goroutine 1
	/usr/local/go/src/runtime/mgc.go:201 +0xa5

goroutine 5 [finalizer wait]:
runtime.gopark(0x198?, 0x1a22c00?, 0x1?, 0xf7?, 0x0?)
	/usr/local/go/src/runtime/proc.go:398 +0xce fp=0xc000086620 sp=0xc000086600 pc=0x44e64e
runtime.runfinq()
	/usr/local/go/src/runtime/mfinal.go:193 +0x107 fp=0xc0000867e0 sp=0xc000086620 pc=0x42d827
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc0000867e8 sp=0xc0000867e0 pc=0x47e2a1
created by runtime.createfing in goroutine 1
	/usr/local/go/src/runtime/mfinal.go:163 +0x3d

goroutine 14 [GC worker (idle)]:
runtime.gopark(0x139c570cd3?, 0x41a02b?, 0x37?, 0x94?, 0xc00020bb00?)
	/usr/local/go/src/runtime/proc.go:398 +0xce fp=0xc000088750 sp=0xc000088730 pc=0x44e64e
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1295 +0xe5 fp=0xc0000887e0 sp=0xc000088750 pc=0x430385
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc0000887e8 sp=0xc0000887e0 pc=0x47e2a1
created by runtime.gcBgMarkStartWorkers in goroutine 1
	/usr/local/go/src/runtime/mgc.go:1219 +0x1c

goroutine 15 [IO wait]:
runtime.gopark(0x64?, 0xb?, 0x0?, 0x0?, 0x7?)
	/usr/local/go/src/runtime/proc.go:398 +0xce fp=0xc000099c98 sp=0xc000099c78 pc=0x44e64e
runtime.netpollblock(0x4932b8?, 0x417906?, 0x0?)
	/usr/local/go/src/runtime/netpoll.go:564 +0xf7 fp=0xc000099cd0 sp=0xc000099c98 pc=0x447057
internal/poll.runtime_pollWait(0x7f98680deeb0, 0x72)
	/usr/local/go/src/runtime/netpoll.go:343 +0x85 fp=0xc000099cf0 sp=0xc000099cd0 pc=0x478b25
internal/poll.(*pollDesc).wait(0xc0004487e0?, 0xc0001c7000?, 0x1)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:84 +0x27 fp=0xc000099d18 sp=0xc000099cf0 pc=0x4b7627
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc0004487e0, {0xc0001c7000, 0x1000, 0x1000})
	/usr/local/go/src/internal/poll/fd_unix.go:164 +0x27a fp=0xc000099db0 sp=0xc000099d18 pc=0x4b891a
os.(*File).read(...)
	/usr/local/go/src/os/file_posix.go:29
os.(*File).Read(0xc0003edde8, {0xc0001c7000?, 0x0?, 0x0?})
	/usr/local/go/src/os/file.go:118 +0x52 fp=0xc000099df0 sp=0xc000099db0 pc=0x4c3c12
bufio.(*Scanner).Scan(0xc000468180)
	/usr/local/go/src/bufio/scan.go:214 +0x81b fp=0xc000099ec8 sp=0xc000099df0 pc=0x53e55b
github.com/NVIDIA/dcgm-exporter/pkg/stdout.Capture.func2()
	/go/src/github.com/NVIDIA/dcgm-exporter/pkg/stdout/capture.go:59 +0x45 fp=0xc000099fe0 sp=0xc000099ec8 pc=0x160fb85
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc000099fe8 sp=0xc000099fe0 pc=0x47e2a1
created by github.com/NVIDIA/dcgm-exporter/pkg/stdout.Capture in goroutine 1
	/go/src/github.com/NVIDIA/dcgm-exporter/pkg/stdout/capture.go:58 +0x1e8

goroutine 21 [IO wait]:
runtime.gopark(0x87b4991ae8d99fa3?, 0xb?, 0x0?, 0x0?, 0x10?)
	/usr/local/go/src/runtime/proc.go:398 +0xce fp=0xc0004a55c8 sp=0xc0004a55a8 pc=0x44e64e
runtime.netpollblock(0x4932b8?, 0x417906?, 0x0?)
	/usr/local/go/src/runtime/netpoll.go:564 +0xf7 fp=0xc0004a5600 sp=0xc0004a55c8 pc=0x447057
internal/poll.runtime_pollWait(0x7f98680decc0, 0x72)
	/usr/local/go/src/runtime/netpoll.go:343 +0x85 fp=0xc0004a5620 sp=0xc0004a5600 pc=0x478b25
internal/poll.(*pollDesc).wait(0xc000468480?, 0xc0004ce000?, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:84 +0x27 fp=0xc0004a5648 sp=0xc0004a5620 pc=0x4b7627
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc000468480, {0xc0004ce000, 0x3800, 0x3800})
	/usr/local/go/src/internal/poll/fd_unix.go:164 +0x27a fp=0xc0004a56e0 sp=0xc0004a5648 pc=0x4b891a
net.(*netFD).Read(0xc000468480, {0xc0004ce000?, 0xc0004cfd71?, 0x1a?})
	/usr/local/go/src/net/fd_posix.go:55 +0x25 fp=0xc0004a5728 sp=0xc0004a56e0 pc=0x635525
net.(*conn).Read(0xc0003ec0f8, {0xc0004ce000?, 0x68b1f7?, 0xc000462c38?})
	/usr/local/go/src/net/net.go:179 +0x45 fp=0xc0004a5770 sp=0xc0004a5728 pc=0x646705
net.(*TCPConn).Read(0xc0004a5808?, {0xc0004ce000?, 0xc00048a840?, 0x18?})
	<autogenerated>:1 +0x25 fp=0xc0004a57a0 sp=0xc0004a5770 pc=0x658ee5
crypto/tls.(*atLeastReader).Read(0xc00048a840, {0xc0004ce000?, 0xc00048a840?, 0x0?})
	/usr/local/go/src/crypto/tls/conn.go:805 +0x3b fp=0xc0004a57e8 sp=0xc0004a57a0 pc=0x68effb
bytes.(*Buffer).ReadFrom(0xc000462d28, {0x1ca8120, 0xc00048a840})
	/usr/local/go/src/bytes/buffer.go:211 +0x98 fp=0xc0004a5840 sp=0xc0004a57e8 pc=0x50e398
crypto/tls.(*Conn).readFromUntil(0xc000462a80, {0x1ca63c0?, 0xc0003ec0f8}, 0x1a94?)
	/usr/local/go/src/crypto/tls/conn.go:827 +0xde fp=0xc0004a5880 sp=0xc0004a5840 pc=0x68f1de
crypto/tls.(*Conn).readRecordOrCCS(0xc000462a80, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:625 +0x250 fp=0xc0004a5c20 sp=0xc0004a5880 pc=0x68c7b0
crypto/tls.(*Conn).readRecord(...)
	/usr/local/go/src/crypto/tls/conn.go:587
crypto/tls.(*Conn).Read(0xc000462a80, {0xc0004b3000, 0x1000, 0x8ed485?})
	/usr/local/go/src/crypto/tls/conn.go:1369 +0x158 fp=0xc0004a5c90 sp=0xc0004a5c20 pc=0x692a78
bufio.(*Reader).Read(0xc0000b2fc0, {0xc000194d60, 0x9, 0x28fc210?})
	/usr/local/go/src/bufio/bufio.go:244 +0x197 fp=0xc0004a5cc8 sp=0xc0004a5c90 pc=0x53bc37
io.ReadAtLeast({0x1ca6100, 0xc0000b2fc0}, {0xc000194d60, 0x9, 0x9}, 0x9)
	/usr/local/go/src/io/io.go:335 +0x90 fp=0xc0004a5d10 sp=0xc0004a5cc8 pc=0x4b18b0
io.ReadFull(...)
	/usr/local/go/src/io/io.go:354
golang.org/x/net/http2.readFrameHeader({0xc000194d60, 0x9, 0x2993380?}, {0x1ca6100?, 0xc0000b2fc0?})
	/go/pkg/mod/golang.org/x/net@v0.20.0/http2/frame.go:237 +0x65 fp=0xc0004a5d60 sp=0xc0004a5d10 pc=0x8d7645
golang.org/x/net/http2.(*Framer).ReadFrame(0xc000194d20)
	/go/pkg/mod/golang.org/x/net@v0.20.0/http2/frame.go:498 +0x85 fp=0xc0004a5e08 sp=0xc0004a5d60 pc=0x8d7d85
golang.org/x/net/http2.(*clientConnReadLoop).run(0xc0004a5f98)
	/go/pkg/mod/golang.org/x/net@v0.20.0/http2/transport.go:2275 +0x11f fp=0xc0004a5f60 sp=0xc0004a5e08 pc=0x8ea41f
golang.org/x/net/http2.(*ClientConn).readLoop(0xc000002480)
	/go/pkg/mod/golang.org/x/net@v0.20.0/http2/transport.go:2170 +0x65 fp=0xc0004a5fc8 sp=0xc0004a5f60 pc=0x8e99a5
golang.org/x/net/http2.(*Transport).newClientConn.func3()
	/go/pkg/mod/golang.org/x/net@v0.20.0/http2/transport.go:821 +0x25 fp=0xc0004a5fe0 sp=0xc0004a5fc8 pc=0x8e2825
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc0004a5fe8 sp=0xc0004a5fe0 pc=0x47e2a1
created by golang.org/x/net/http2.(*Transport).newClientConn in goroutine 20
	/go/pkg/mod/golang.org/x/net@v0.20.0/http2/transport.go:821 +0xcbe

rax    0x0
rbx    0x7f986060e360
rcx    0x7f98af80ca1c
rdx    0x1
rdi    0x0
rsi    0x3bd9940
rbp    0x4
rsp    0x7f9862bfb940
r8     0x90800
r9     0x3bd9940
r10    0x0
r11    0x287
r12    0xffffffffffffff78
r13    0x2
r14    0x0
r15    0x0
rip    0x7f98af7d96aa
rflags 0x10202
cs     0x33
fs     0x0
gs     0x0
```

### What did you expect to happen?

Healthy dcgm-exporter pod

### What is the GPU model?

aws g5.2xlarge

### What is the environment?

EKS via DCGM-Exporter helm chart

### How did you deploy the dcgm-exporter and what is the configuration?

on EKS via DCGM-Exporter helm chart

**Comment by nvvfedorov** [comment]
Can you connect to the shell on the pod and run: `dcgmi discovery -c` ?

**Comment by nvvfedorov** [comment]
@amybachir , Can you try to roll back the DCGM-exporter version to 3.3.3-3.3.1? I want to see if it is a DCGM-exporter version issue or an environment issue. Thank you in advance.

**Comment by DimitrijeManic** [comment]
@nvvfedorov I had run into the same issue with both `3.3.3-3.3.1` and the latest.
I believe this is related to the DataDog suggested configuration 
```
# Format
# If line starts with a '#' it is considered a comment
# DCGM FIELD                                                      ,Prometheus metric type ,help message

# Clocks
DCGM_FI_DEV_SM_CLOCK                                              ,gauge                  ,SM clock frequency (in MHz).
DCGM_FI_DEV_MEM_CLOCK                                             ,gauge                  ,Memory clock frequency (in MHz).

# Temperature
DCGM_FI_DEV_MEMORY_TEMP                                           ,gauge                  ,Memory temperature (in C).
DCGM_FI_DEV_GPU_TEMP                                              ,gauge                  ,GPU temperature (in C).

# Power
DCGM_FI_DEV_POWER_USAGE                                           ,gauge                  ,Power draw (in W).
DCGM_FI_DEV_TOTAL_ENERGY_CONSUMPTION                              ,counter                ,Total energy consumption since boot (in mJ).

# PCIE
DCGM_FI_DEV_PCIE_REPLAY_COUNTER                                   ,counter                ,Total number of PCIe retries.

# Utilization (the sample period varies depending on the product)
DCGM_FI_DEV_GPU_UTIL                                              ,gauge                  ,GPU utilization (in %).
DCGM_FI_DEV_MEM_COPY_UTIL                                         ,gauge                  ,Memory utilization (in %).
DCGM_FI_DEV_ENC_UTIL                                              ,gauge                  ,Encoder utilization (in %).
DCGM_FI_DEV_DEC_UTIL                                              ,gauge                  ,Decoder utilization (in %).

# Errors and violations
DCGM_FI_DEV_XID_ERRORS                                            ,gauge                  ,Value of the last XID error encountered.

# Memory usage
DCGM_FI_DEV_FB_FREE                                               ,gauge                  ,Framebuffer memory free (in MiB).
DCGM_FI_DEV_FB_USED                                               ,gauge                  ,Framebuffer memory used (in MiB).

# NVLink
DCGM_FI_DEV_NVLINK_BANDWIDTH_TOTAL                                ,counter                ,Total number of NVLink bandwidth counters for all lanes.

# VGPU License status
DCGM_FI_DEV_VGPU_LICENSE_STATUS                                   ,gauge                  ,vGPU License status

# Remapped rows
DCGM_FI_DEV_UNCORRECTABLE_REMAPPED_ROWS                           ,counter                ,Number of remapped rows for uncorrectable errors
DCGM_FI_DEV_CORRECTABLE_REMAPPED_ROWS                             ,counter                ,Number of remapped rows for correctable errors
DCGM_FI_DEV_ROW_REMAP_FAILURE                                     ,gauge                  ,Whether remapping of rows has failed

# DCP metrics
DCGM_FI_PROF_PCIE_TX_BYTES                                        ,counter                ,The number of bytes of active pcie tx data including both header and payload.
DCGM_FI_PROF_PCIE_RX_BYTES                                        ,counter                ,The number of bytes of active pcie rx data including both header and payload.
DCGM_FI_PROF_GR_ENGINE_ACTIVE                                     ,gauge                  ,Ratio of time the graphics engine is active (in %).
DCGM_FI_PROF_SM_ACTIVE                                            ,gauge                  ,The ratio of cycles an SM has at least 1 warp assigned (in %).
DCGM_FI_PROF_SM_OCCUPANCY                                         ,gauge                  ,The ratio of number of warps resident on an SM (in %).
DCGM_FI_PROF_PIPE_TENSOR_ACTIVE                                   ,gauge                  ,Ratio of cycles the tensor (HMMA) pipe is active (in %).
DCGM_FI_PROF_DRAM_ACTIVE                                          ,gauge                  ,Ratio of cycles the device memory interface is active sending or receiving data (in %).
DCGM_FI_PROF_PIPE_FP64_ACTIVE                                     ,gauge                  ,Ratio of cycles the fp64 pipes are active (in %).
DCGM_FI_PROF_PIPE_FP32_ACTIVE                                     ,gauge                  ,Ratio of cycles the fp32 pipes are active (in %).
DCGM_FI_PROF_PIPE_FP16_ACTIVE                                     ,gauge                  ,Ratio of cycles the fp16 pipes are active (in %).

# Datadog additional recommended fields
DCGM_FI_DEV_COUNT                                                 ,counter                ,Number of Devices on the node.
DCGM_FI_DEV_FAN_SPEED                                             ,gauge                  ,Fan speed for the device in percent 0-100.
DCGM_FI_DEV_SLOWDOWN_TEMP                                         ,gauge                  ,Slowdown temperature for the device.
DCGM_FI_DEV_POWER_MGMT_LIMIT                                      ,gauge                  ,Current power limit for the device.
DCGM_FI_DEV_PSTATE                                                ,gauge                  ,Performance state (P-State) 0-15. 0=highest
DCGM_FI_DEV_FB_TOTAL                                              ,gauge                  ,
DCGM_FI_DEV_FB_RESERVED                                           ,gauge                  ,
DCGM_FI_DEV_FB_USED_PERCENT                                       ,gauge                  ,
DCGM_FI_DEV_CLOCK_THROTTLE_REASONS                                ,gauge                  ,Current clock throttle reasons (bitmask of DCGM_CLOCKS_THROTTLE_REASON_*)

DCGM_FI_PROCESS_NAME                                              ,label                  ,The Process Name.
DCGM_FI_CUDA_DRIVER_VERSION                                       ,label                  ,
DCGM_FI_DEV_NAME                                                  ,label                  ,
DCGM_FI_DEV_MINOR_NUMBER                                          ,label                  ,
DCGM_FI_DRIVER_VERSION                                            ,label                  ,
DCGM_FI_DEV_BRAND                                                 ,label                  ,
DCGM_FI_DEV_SERIAL                                                ,label                  ,
```

Using the config above I get a SIGSEGV.
However if I comment out `DCGM_FI_DEV_COUNT`, `DCGM_FI_PROCESS_NAME`, & `DCGM_FI_CUDA_DRIVER_VERSION` things start without issues. 

Though CPU metrics aren't included.
```
msg="Not collecting CPU metrics; no fields to watch for device type: 7"
msg="Not collecting CPU Core metrics; no fields to watch for device type: 8"
```

**Comment by nvvfedorov** [comment]
Thank you for reporting the issue, we will check.

**Comment by wixaw** [comment]
hello @nvvfedorov 
dcgm-exporter is broken since golang update in 1.21.9 ( work on 1.20.12 )
Thanks

**Comment by nvvfedorov** [comment]
@wixaw Thank you for the update.

**Comment by Dudesons** [comment]
Hi, @wixaw @nvvfedorov  I have the same issue.
```
2024/08/07 12:35:13 maxprocs: Leaving GOMAXPROCS=8: CPU quota undefined
time="2024-08-07T12:35:13Z" level=info msg="Starting dcgm-exporter"
time="2024-08-07T12:35:13Z" level=info msg="DCGM successfully initialized!"
time="2024-08-07T12:35:13Z" level=info msg="Collecting DCP Metrics"
time="2024-08-07T12:35:13Z" level=info msg="Initializing system entities of type: GPU"
time="2024-08-07T12:35:14Z" level=info msg="Initializing system entities of type: NvSwitch"
time="2024-08-07T12:35:14Z" level=info msg="Not collecting NvSwitch metrics; no switches to monitor"
time="2024-08-07T12:35:14Z" level=info msg="Initializing system entities of type: NvLink"
time="2024-08-07T12:35:14Z" level=info msg="Not collecting NvLink metrics; no switches to monitor"
time="2024-08-07T12:35:14Z" level=info msg="Initializing system entities of type: CPU"
SIGSEGV: segmentation violation
PC=0x7f232cd1b6aa m=8 sigcode=1
signal arrived during cgo execution

goroutine 1 [syscall]:
runtime.cgocall(0x163c000, 0xc0005bbc48)
	/usr/local/go/src/runtime/cgocall.go:157 +0x4b fp=0xc0005bbc20 sp=0xc0005bbbe8 pc=0x41816b
github.com/NVIDIA/go-dcgm/pkg/dcgm._Cfunc_dcgmGetCpuHierarchy(0x7fffffff, 0xc000214000)
	_cgo_gotypes.go:1115 +0x4b fp=0xc0005bbc48 sp=0xc0005bbc20 pc=0x7c932b
github.com/NVIDIA/go-dcgm/pkg/dcgm.GetCpuHierarchy()
	/go/pkg/mod/github.com/!n!v!i!d!i!a/go-dcgm@v0.0.0-20240118201113-3385e277e49f/pkg/dcgm/cpu.go:42 +0x6b fp=0xc0005bc8f8 sp=0xc0005bbc48 pc=0x7cbc2b
github.com/NVIDIA/dcgm-exporter/pkg/dcgmexporter.InitializeCPUInfo({0x0, {{{0x0, {...}, {...}, 0x0, {...}, {...}, {...}, {...}}, {0x0, ...}, ...}, ...}, ...}, ...)

...
```

I tried to comment lines that you indicated from the datadog setup, after that the pod can start without crash.
There is a solution to have all datadog configuration working or not ?
I'm using the image `nvcr.io/nvidia/k8s/dcgm-exporter:3.3.7-3.5.0-ubuntu22.04` on EKS `1.30`

**Comment by Dudesons** [comment]
> The log messages don't correspond to the latest version of dcgm-exporter, see the comment on this issue: [#242 (comment)](https://github.com/NVIDIA/dcgm-exporter/issues/242#issuecomment-2195720254). The backtrace corresponds to an older issue that has been fixed. I suspect your version of dcgm-exporter is not actually the latest.

ok but I have the impression to use the latest release, the image in my daemonset is: `nvcr.io/nvidia/k8s/dcgm-exporter:3.3.7-3.5.0-ubuntu22.04`

Am i wrong ?

**Comment by MuriukiPM** [comment]
Seeing this issue on version `3.3.9-3.6.1`. also using Datadog and running on EKS. Same exact observation as @DimitrijeManic 
The same workaround also worked for me, the exporter pod runs ok.
